version: '3.8'

services:
  nodeblog:
    image: 711771546343.dkr.ecr.eu-north-1.amazonaws.com/nodeblog:1.0
    ports:
      - 3000:5050

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ayeNyeinSan
      MONGO_INITDB_ROOT_PASSWORD: test123

  #mongo-express:
    #image: mongo-express
    #restart: always
    #ports:
      #- 8081:8081
    #environment:
        #ME_CONFIG_MONGODB_ADMINUSERNAME: ayeNyeinSan
        #ME_CONFIG_MONGODB_ADMINPASSWORD: test123
        #ME_CONFIG_MONGODB_SERVER: mongo
        #ME_CONFIG_MONGODB_URL: mongodb://ayeNyeinSan:test123@mongo:27017/