version: '3.8'

services:
  nodeblog:
    image:  29ayenyeinsan/nodeblogg
    ports:
      - 3000:5050



  #mongo-express:
    #image: mongo-express
    #restart: always
    #ports:
      #- 8081:8081
    #environment:
        #ME_CONFIG_MONGODB_ADMINUSERNAME: ayeNyeinSan
        #ME_CONFIG_MONGODB_ADMINPASSWORD: test123
        #ME_CONFIG_MONGODB_SERVER: mongo
        #ME_CONFIG_MONGODB_URL: mongodb://ayeNyeinSan:test123@mongo:27017/