
name: Custom feature template
description: File a feature report
title: "[Feature]:"
labels: '[Feature]:'
assignees: 
  - aye-nyeinsan
  - AyeNyeinSanISRubi
body:
  - type: textarea
    id: featureDetails
    attributes:
      label: "Explain about Feature Details."
      description: "What do you want to explain?"
      placeholder: report in here.
    validations:
      required: true
     



